name: build and deploy docs

on:
  push:
    branches: ['main']
    paths:
      - 'docs/**'

jobs:
  build-and-deploy-docs:
    
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore tools
      run: dotnet tool restore
    - name: make script executable
      run: chmod u+x build.sh
    - name: Build docs
      working-directory: ./
      run: ./build.sh builddocs
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: ./output # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch